/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/airplane/model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Airplane = (props) => {
  const { nodes, materials } = useGLTF("./models/airplane/planeur.glb");

  return (
    <>
      <group {...props} dispose={null} rotation-y={Math.PI}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
        />
      </group>
    </>
  );
};

export default Airplane;

useGLTF.preload("./models/airplane/planeur.glb");
